# Generated by Django 5.1.15 on 2026-05-28 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_user_account'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('payment_pending', 'Payment Pending Verification'), ('payment_rejected', 'Payment Rejected'), ('rent_reminder', 'Rent Reminder'), ('arrears_notice', 'Arrears Notice'), ('lease_expiry', 'Lease Expiry'), ('maintenance_update', 'Maintenance Update')], max_length=64),
        ),
    ]
