# Generated by Django 5.1.15 on 2026-06-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('payment_pending', 'Payment Pending Verification'), ('payment_rejected', 'Payment Rejected'), ('rent_reminder', 'Rent Reminder'), ('arrears_notice', 'Arrears Notice'), ('lease_expiry', 'Lease Expiry'), ('maintenance_update', 'Maintenance Update'), ('tenant_update', 'Tenant Update')], max_length=64),
        ),
    ]
