# Generated by Django 5.1.15 on 2026-05-28 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_user_account'),
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='lease',
            name='expected_move_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='grace_period_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lease',
            name='late_fee_type',
            field=models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='lease',
            name='late_fee_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lease',
            name='notice_given_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='renewed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='leases.lease'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('notice_given', 'Notice Given'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='active', max_length=32),
        ),
    ]
