# Generated by Django 5.1.15 on 2026-06-04 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_accountant_role'),
        ('leases', '0002_lease_account_lease_expected_move_out_date_and_more'),
        ('properties', '0003_property_account'),
        ('tenants', '0004_tenant_damages_checked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant',), name='one_active_lease_per_tenant'),
        ),
    ]
