# Generated by Django 5.1.15 on 2026-05-27 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='caretakers',
            field=models.ManyToManyField(blank=True, related_name='assigned_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
