# Generated by Django 5.1.15 on 2026-05-28 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='enable_cash_collections',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='enable_expenses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='enable_late_fees',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='enable_maintenance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='enable_payment_claims',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='enable_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='enable_tenant_portal',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.TextField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.account')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
