# Generated by Django 5.1.15 on 2026-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_enable_cash_collections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='enable_utilities',
            field=models.BooleanField(default=True),
        ),
    ]
