# Generated by Django 5.1.15 on 2026-06-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_enable_utilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('landlord', 'Landlord'), ('caretaker', 'Caretaker')], max_length=32, unique=True),
        ),
    ]
