# Generated by Django 5.1.15 on 2026-05-28 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_user_account'),
        ('tenants', '0002_tenant_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='deposit_refund_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('partial', 'Partial Refund'), ('refunded', 'Refunded'), ('withheld', 'Withheld')], default='not_applicable', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='move_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('notice_given', 'Notice Given'), ('vacated', 'Vacated')], default='active', max_length=32),
        ),
    ]
