# Generated by Django 5.1.15 on 2026-06-03 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_enable_utilities'),
        ('payments', '0004_utilitycharge'),
        ('tenants', '0003_tenant_account_tenant_deposit_refund_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='damages_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='final_balance_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='keys_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='move_out_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='unit_ready_for_next_tenant',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PromiseToPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promised_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promised_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('kept', 'Kept'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promises_to_pay', to='accounts.account')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_promises_to_pay', to=settings.AUTH_USER_MODEL)),
                ('rent_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promises_to_pay', to='payments.rentcharge')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises_to_pay', to='tenants.tenant')),
            ],
            options={
                'ordering': ['promised_date', '-created_at'],
            },
        ),
    ]
