# Generated by Django 5.1.15 on 2026-06-08 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_accountant_role'),
        ('tenants', '0004_tenant_damages_checked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('account', 'phone_number'), name='unique_tenant_phone_per_account'),
        ),
    ]
