# Generated by Django 5.1.15 on 2026-05-28 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_user_account'),
        ('payments', '0002_cashcollection_paymentclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcollection',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentclaim',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_claims', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='paymentclaim',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentclaim',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='rentcharge',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rent_charges', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='rentcharge',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
