# Generated by Django 5.1.15 on 2026-06-03 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_enable_utilities'),
        ('leases', '0002_lease_account_lease_expected_move_out_date_and_more'),
        ('payments', '0003_cashcollection_account_payment_account_and_more'),
        ('properties', '0003_property_account'),
        ('tenants', '0003_tenant_account_tenant_deposit_refund_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utility_type', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('garbage', 'Garbage'), ('security', 'Security'), ('service_charge', 'Service Charge'), ('other', 'Other')], max_length=32)),
                ('billing_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utility_charges', to='accounts.account')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_charges', to='leases.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_charges', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_charges', to='tenants.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_charges', to='properties.unit')),
            ],
            options={
                'ordering': ['-billing_month', 'utility_type'],
            },
        ),
    ]
