# Generated by Django 5.1.15 on 2026-06-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_utilitycharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentclaim',
            name='pasted_message',
            field=models.TextField(blank=True),
        ),
    ]
